nzbgetcom/nzbget

README.md
- added: macos build status badge to README
=> add: macos build status badge

.github/workflows/docker.yml, .gitignore, README.md, docker/Dockerfile, docker/README.md, docker/docker-compose.yml, docker/entrypoint.sh
- added docker support for NZBGet
- added workflow for build and push to DockerHub and GitHub
=> Docker support

.github/workflows/linux.yml
- aarch64 architecture added for linux build
=> Add aarch64 for linux build

docker/Dockerfile
Change unpack commands for docker builds to match binaries in alpine base image packages.
This will aso fix #77
=> Fix docker unpack commands

README.md
Adding links to Issue and Discussion answering fresh questions by users on migration from older setups
Use MD preview to smoke test
=> extra information on how to migrate

README.md, linux/build-info.md
- update links to build instructions in README
- convert linux cross-compiling instructions to md format
=> Update build instructions

.github/workflows/linux.yml
- mipseb / mipsel / ppc6xx / ppc500 architectures added for linux build
=> Add mipseb mipsel ppc6xx ppc500 architectures to linux build

daemon/util/NString.cpp, lib/par2/reedsolomon.h
- fixed possible memory corruption inspired by reports from nzbget-ng
=> Fix: possible memory corruption

.github/workflows/docker.yml
- removed automatic build and push docker images on main branch and tags
- added workflow_dispatch trigger to docker workflow
=> Tweak docker CI/CD

.github/workflows/linux.yml, .github/workflows/qnap-repack.yml, .github/workflows/qnap.yml, .github/workflows/synology.yml
- changed CI jobs tags to run NAS builds on dedicated runner to speedup
=> Separate NAS runner (Synology/QNAP)

.github/workflows/linux.yml, linux/installer.sh
- added linux builds for riscv64
- removed debug build from custom branches
- inspired by #162 
- tested by @phnzb on QEMU RISC-V VM (Ubuntu 22.04)
- tested by @sanderjo on RISCV64 SBC
=> RISC-V 64 Support

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, .github/ISSUE_TEMPLATE/03_build.yml, .github/ISSUE_TEMPLATE/04_extension.yml, .github/ISSUE_TEMPLATE/config.yml
Basic issue templates, including:
- config
- bug report
- feature requests
- compiling/ building
- and extensions (unfinished)
Related discussion https://github.com/nzbgetcom/nzbget/discussions/157
[Cloned repo](https://github.com/luckedea/nzbgetissuestest/issues/new/choose)
=> issue templates

CMakeLists.txt, configure.ac, nzbget.vcxproj, osx/NZBGet-Info.plist, windows/nzbget-setup.nsi, windows/resources/nzbget.rc
- increased develop (testing) version to 23.1
=> Increase develop version to 23.1

webui/config.js, webui/index.html
- fixed license links
- fixed links from nzbget.conf in webui
Tested on Windows 11
=> Fix and update links in webui

.github/workflows/docker.yml, docker/Dockerfile, docker/docker-compose.yml, docker/entrypoint.sh
- updated base image version to `alpine:3.19.1`
- updated unrar to 7.0
- updated 7zip to 23.01 (and switched from p7zip)
- migrated to CMake build
- fixed container timezone (#213)
- fixed #81
- workflow: push to ghcr.io on develop/main/tags push only
- workflow: update Docker Hub description on main push only
tested by @phnzb on
- linux/amd64: Ubuntu 22.04.4 LTS x64 / Docker 26.0.0
- linux/arm64: Debian 12.5 aarch64 / Docker 20.10.24
- linux/arm/v7: Debian 12.2 armhf / Docker 26.0.0
=> Docker fixes and updates

docker/entrypoint.sh
Fix docker fresh install (bug caused by removing recursively changing permissions in #218 
@phnzb Ubuntu 22.04.4 LTS / 26.0.0
=> Docker: fix fresh install

ChangeLog.md, README.md
=> v24.1 changelog

CMakeLists.txt, configure.ac, nzbget.vcxproj, osx/NZBGet-Info.plist
=> Promote version to v24.2

README.md
- added LinuxServer.io docker images information
=> Add LinuxServer.io information

qnap/package/package_routines, qnap/package/shared/nzbget.sh
- fixes https://github.com/nzbgetcom/nzbget/issues/279
by @phnzb  on QNAP TS-253E (QTS 5.1.4.2596)
=> QNAP: don't overwrite existing config file when upgrading QPKG

README.md, windows/pkgs-info.md
- added documentation about installation Windows packages via package managers (winget and chocolatey)
=> Windows: package managers documentation

tests/util/CMakeLists.txt, tests/util/FileSystemTest.cpp
- fixed the FileSystem tests build on POSIX
Linux Debian 12
=> Fix: FileSystem tests on POSIX

daemon/remote/BinRpc.cpp
=> Fix: POSIX build

CMakeLists.txt, osx/NZBGet-Info.plist
- promoted the new v24.3 testing version
=> Promote the new v24.3 testing version

docs/api/API.md, docs/api/APPEND.md, docs/api/EDITQUEUE.md, docs/api/HISTORY.md, docs/api/LISTGROUPS.md, docs/api/SERVERVOLUMES.md, docs/extensions/EXTENSIONS.md, docs/extensions/SCAN.md, docs/usage/RSS.md
- fixed API link
- added RSS.md mock file
- fixed typo
- added missing closing `**`
=> Fix: API link, typo, missing closing **

docs/api/API.md, docs/api/RELOAD.md, docs/api/SCAN.md, docs/api/SHUTDOWN.md
=> Fix: typos

daemon/main/Options.cpp, daemon/main/Options.h, daemon/main/nzbget.cpp, tests/extension/ExtensionManagerTest.cpp, tests/main/OptionsTest.cpp
- added directory check before running the daemon
=> Fix: checking dirs before daemon run

webui/index.html, webui/system-info.js
- added `Write buffer` table raw to the System table
Windows 10
=> Add: Write buffer table raw to the System table

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, ChangeLog.md, README.md
- added v24.3 changelog
- updated the issue template
=> Add: v24.3 changelog

CMakeLists.txt, osx/NZBGet-Info.plist
- promoted the new v24.4 testing version
=> Promote the new v24.4 testing version

docs/HOW_TO_USE.md
- added to docs/HOW_TO_USE.md systemd information
=> Update docs with systemd information

tests/postprocess/ParCheckerTest.cpp, tests/postprocess/ParRenamerTest.cpp, tests/postprocess/RarReaderTest.cpp, tests/postprocess/RarRenamerTest.cpp
- use cross-platformic path separators 
- Windows 11
=> Refactor: postprocess test paths

cmake/par2-turbo.cmake
- using the tag with version for more convenient Par2-turbo updates
=> Use Par2-turbo version tag

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, ChangeLog.md, README.md
- updated changelog
- updated README
- updated the issue templates
=> v24.4 release preparation

CMakeLists.txt, osx/NZBGet-Info.plist
- promote v24.5-testing version
=> Promote v24.5-testing version

SECURITY.md
Added SECURITY.md
Created security@nzbget.com
Enabled vulnerability issues.
Inspired by
https://github.com/nzbgetcom/nzbget/discussions/446 and https://github.com/nzbget/nzbget/issues/833
=> security.md

README.md
- added information about ASUSTOR NAS package to README.md
=> Add ASUSTOR package information

ChangeLog.md
- fixed nzbget version in changelog
=> Fix: nzbget version in changelog

.github/workflows/build.yml
- reverted runner for build.yml / generate-signatures step to ubuntu-22.04
- fixes #461
=> Fix: generate updater signatures

.github/workflows/osx.yml, cmake/common.cmake, cmake/config.h.in, cmake/windows.cmake, daemon/main/StackTrace.cpp, lib/regex/regex.c, osx/build-nzbget.sh
- fixed stacktrace logging at Segmentation Fault
- added macOS debug build
- Windows 11
=> Fix: stacktrace logging at Segmentation Fault

cmake/boost.cmake, cmake/par2-turbo.cmake, tests/postprocess/CMakeLists.txt
- fixed build using CMake Ninja generator
- fixed tests build failure with  -DDISABLE_PARCHECK=yes 
=> Fix: build using CMake Ninja generator and the tests build failure with -DDISABLE_PARCHECK=yes

docs/api/API.md
- updated the API.md file with a link to the new `testnetworkspeed` API method doc
=> Update api doc

daemon/postprocess/Cleanup.cpp
- fixed macOS and FreeBSD builds
=> Fix: macOS, FreeBSD builds

webui/config.js, webui/messages.js, webui/system-info.js
- fixed: incorrect method usage in webui
- WIndows 11 / Chrome
=> Fix: incorrect method usage in webui

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, ChangeLog.md, README.md
- added v24.6 changelog
- updated issue templates
=> Add: v24.6 changelog

.github/workflows/docker.yml
- added missed checkout for Update Docker Hub Description step
=> Fix: docker buld for main branch

CMakeLists.txt, osx/NZBGet-Info.plist
- promoted new 24.7 testing version
=> Promote new v24.7 testing version

ChangeLog.md, README.md
- added changelog v24.7
- updated the pipeline build badges in README.md
=> Add: v24.7 changelog

README.md
- added information about TrueNAS package
- completes #494
=> Add TrueNAS readme information

daemon/queue/DirectRenamer.cpp
- Fixed DirectUnpack cancellation because files were prematurely renamed to *.rar. Renaming incomplete files can cause DirectUnpack to fail, as it may try to unpack incomplete .rar files.
=> Fix: DirectUnpack cancellation 

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, ChangeLog.md
- added v24.8 changelog
- updated the issue templates
=> v24.8 changelog

README.md
=> Add: v24.8 label

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, CMakeLists.txt, ChangeLog.md, README.md, daemon/queue/DirectRenamer.cpp, daemon/util/ScriptController.cpp, daemon/util/Util.cpp, osx/NZBGet-Info.plist
- Features:
- TrueNAS Scale support [#494](https://github.com/nzbgetcom/nzbget/issues/494)
- Bug fixes:
- Fixed application updates on Windows [#528](https://github.com/nzbgetcom/nzbget/pull/528)
- Fixed DirectUnpack cancellation [#530](https://github.com/nzbgetcom/nzbget/pull/530)
=> Release v24.8

CMakeLists.txt, osx/NZBGet-Info.plist
=> Promote v24.9-testing

.github/workflows/android.yml, .github/workflows/build.yml, .github/workflows/flatpak.yml, .github/workflows/linux-pkg.yml, .github/workflows/linux.yml, .github/workflows/osx.yml, .github/workflows/qnap-repack.yml, .github/workflows/windows.yml, README.md, linux/flatpak/README.md, linux/flatpak/build-flatpak.sh, linux/flatpak/build-info.md, linux/flatpak/com.nzbget.nzbget.desktop, linux/flatpak/com.nzbget.nzbget.metainfo.xml, linux/flatpak/com.nzbget.nzbget.svg, linux/flatpak/com.nzbget.nzbget.yml, linux/flatpak/nzbget-launcher.sh
- added Flatpak support (#490 partially complete)
- fixed workflows race conditions with artifacts handling
by @phnzb:
- Debian GNU/Linux 12.10
- Ubuntu 24.04.2 LTS
=> Flatpak support

webui/statistics.js, webui/util.js
- Improved unit readability to avoid potential confusion
- Chrome 135
- Firefox 137
- Safari 18
=> Feature: Improve unit formatting on the statistics page

.github/workflows/snap.yml, .gitignore, linux/snap/snapcraft.yaml
- added snap manifest 
- added release snap workflow
- partially completes #490 
by @phnzb:
- Ubuntu 24.04.2 LTS x86_64
- Ubuntu 22.04.2 LTS aarch64
- Debian GNU/Linux 12.10 x86_64
=> Snap support

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, CMakeLists.txt, ChangeLog.md, README.md, osx/NZBGet-Info.plist
- added nzbget v25 changelog
- refactored the "Installation" section in README.md
- updated issue templates
=> Add: v25 changelog

docs/POSIX.md, docs/WINDOWS.md
- fixed text formatting
- fixed typos
=> Fix: text formatting and typos

daemon/feed/FeedFile.cpp, daemon/feed/FeedFile.h, daemon/util/Util.cpp, tests/feed/FeedFileTest.cpp, tests/testdata/feed/feed.xml, tests/util/UtilTest.cpp
- improved memory safety and prevent potential undefined behavior (UB)
- added more unit tests
- macOS Ventura amd64
- Docker amd64/arm64
=> Fix: RSS feed segfault

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, ChangeLog.md
- added v25.1 changelog
- updated issue templates
=> v25.1 changelog

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/03_build.yml, .github/workflows/docker-debug.yml, .github/workflows/docker.yml, CMakeLists.txt, ChangeLog.md, daemon/connect/Connection.cpp, daemon/queue/DiskState.cpp, daemon/queue/DownloadInfo.h, docker/Dockerfile, docker/README.md, docker/docker-compose.yml, osx/NZBGet-Info.plist
=> Release v25.2

.github/workflows/osx.yml
- libraries downgraded to support macOS Mojave (10.14) minimum 
- fixes https://github.com/nzbgetcom/nzbget/issues/610
@phnzb - macOS Mojave 10.14.6
=> Fix: macOS x64 Mojave support

daemon/main/Options.cpp, daemon/main/Options.h, daemon/postprocess/DirectUnpack.cpp, daemon/postprocess/Unpack.cpp, nzbget.conf
As discussed [here](https://github.com/nzbgetcom/nzbget/issues/570)
=> Add an option to disable the _unpack intermediate folder

webui/index.html, webui/index.js, webui/style.css
- Enabled the search bar on small screens, allowing users on mobile devices to easily search for content;
- Improved the layout of the settings page to provide a better user experience on small screens.
Browsers:
- Google Chrome;
- Safari;
- Edge.
=> Feat: enable the search bar on small screens

docs/FINDING_BEST_TLS_CIPHER.md, docs/PERFORMANCE.md, docs/UNPACKING.md
- Updated the performance tips doc;
- Added a document on finding the best TLSv1.3 ciphers.
=> Docs: Update the performance tips doc

ChangeLog.md
=> Add: v25.4 changelog
